version: 2
updates:
  # Maintain GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  # Maintain root Node dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  # Maintain Pulumi infrastructure dependencies
  - package-ecosystem: "npm"
    directory: "/infra/pulumi"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-infra)"
